version: '3.5'

networks:
  CryptoNetwork:
    name: CryptoNetwork
    ipam:
      config:
        - subnet: 10.20.20.0/24

services:
  db:
    container_name: cryptonginx
    build: .
    image: 'cryptonginx'
    networks:
      CryptoNetwork:
        ipv4_address: 10.20.20.4
    ports:
      - '80:80'
    restart: always
